### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by bytehead**
Some various fixes:
- Missing model declaration
- Wrong namespace in use statement
- Missing RequestToken

### CODE REVIEW

**Comment by richardhj** [comment]
+1
I would be glad to see it on packagist :-)

**Comment by blairwinans** [comment]
Sorry—my GitHub notifications for this repo were been getting routed to the wrong email folder for a while now. Let me see what I can do to get this all working. There are more fixes that need to be put in place in addition to the ones in your PR, but I will get them all sorted... My apologies!

**Comment by bytehead** [comment]
No worries, thanks for the merge! I think, you can now close the issues #2 and #3.

**Comment by blairwinans** [comment]
Will do—still merging some additional changes but once they are set I will close those and add to Packagist... Thanks for the nudge!

**Pull request merged**
